// Case Document Model
// Defines the CaseDocument schema for the database
// Documents attached to cases are only visible to admin and legalOfficer

import mongoose from 'mongoose';

/**
 * Case Document Schema
 * Defines the structure of case document documents in the database
 */
const caseDocumentSchema = mongoose.Schema(
  {
    // Reference to Case this document belongs to
    case: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Case',
      required: [true, 'Case reference is required'],
    },
    // Stored filename (generated by server)
    filename: {
      type: String,
      required: [true, 'Filename is required'],
    },
    // Original filename (from upload)
    originalName: {
      type: String,
      required: [true, 'Original name is required'],
    },
    // File path on server
    filePath: {
      type: String,
      required: [true, 'File path is required'],
    },
    // File MIME type
    fileType: {
      type: String,
      required: [true, 'File type is required'],
    },
    // File size in bytes
    fileSize: {
      type: Number,
      required: [true, 'File size is required'],
    },
    // Reference to User who uploaded the document
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Uploader is required'],
    },
  },
  {
    // Automatically add createdAt and updatedAt timestamps
    timestamps: true,
  }
);

/**
 * Index on case for faster queries when filtering by case
 */
caseDocumentSchema.index({ case: 1 });

/**
 * Index on uploadedBy for faster queries when filtering by uploader
 */
caseDocumentSchema.index({ uploadedBy: 1 });

/**
 * Index on createdAt for sorting
 */
caseDocumentSchema.index({ createdAt: -1 });

// Create and export CaseDocument model
export default mongoose.model('CaseDocument', caseDocumentSchema);

